#!/usr/bin/env php
<?php

use Jackdou\PhpModelGenerator\Application;

require __DIR__ . '/vendor/autoload.php';

// 获取参数
$cfgFile = $argv[1] ?? '';
if (!$cfgFile) {
    echo "please input the config file path." . PHP_EOL;
    die;
}

(new Application($cfgFile))->run();
